# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56737658f2c259aaae49077322ff2206dd6554b3c8be06fe316e07b3e00aa42226d251b1e1136baecc6d91ee6e4996041a4dba4be4890d1531a3737b87cf7174

test:
  secret_key_base: cf7abae5757dbc22435f601310035b9ca0918c279b36542674e0219ebd9ffcd28d4ffc6ab92bd7826195faafec9c8ff350b02a676fdd03b471c59cf2601cdf71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
